import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { configDir, runtimeConfigPath, pythonExe } from "./paths";
import { runAsync } from "./proc";
import { logBootstrap } from "./logger";

export interface RuntimeConfig {
  jwtSecret: string;
  encryptionKey: string;
  pgSuperuserPassword: string;
  firstRunComplete: boolean;
}

// ENCRYPTION_KEY must stay byte-identical across every future launch — it's
// a Fernet key that decrypts stored Google OAuth tokens in the local DB.
// Regenerating it would silently orphan every previously-connected
// integration. jwtSecret/pgSuperuserPassword are equally persisted for the
// same reason: rotating either would invalidate existing sessions / lock
// the app out of its own database.
export async function loadOrCreateRuntimeConfig(): Promise<{ config: RuntimeConfig; isFirstRun: boolean }> {
  if (existsSync(runtimeConfigPath)) {
    const config: RuntimeConfig = JSON.parse(readFileSync(runtimeConfigPath, "utf-8"));
    return { config, isFirstRun: !config.firstRunComplete };
  }

  mkdirSync(configDir, { recursive: true });

  const jwtSecret = randomBytes(32).toString("hex");
  const pgSuperuserPassword = randomBytes(24).toString("hex");
  const encryptionKey = await generateFernetKey();

  const config: RuntimeConfig = {
    jwtSecret,
    encryptionKey,
    pgSuperuserPassword,
    firstRunComplete: false,
  };
  writeRuntimeConfig(config);
  return { config, isFirstRun: true };
}

export function writeRuntimeConfig(config: RuntimeConfig): void {
  writeFileSync(runtimeConfigPath, JSON.stringify(config, null, 2), "utf-8");
}

// Shells out to the staged embeddable Python so the key is generated by the
// exact same `cryptography` version the backend will use to read it back —
// matches the generation command documented in backend/.env.example. This is
// typically the single slowest bootstrap step on a first-ever launch, since
// it's the first time python.exe (and its whole site-packages tree) gets
// touched at all, and antivirus real-time scanning of a freshly-installed
// binary can take a while.
async function generateFernetKey(): Promise<string> {
  logBootstrap("secrets: generating encryption key (first-ever python.exe launch, may take a moment)");
  const result = await runAsync(
    pythonExe,
    ["-c", "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"],
  );
  if (result.status !== 0 || !result.stdout) {
    throw new Error(`Failed to generate encryption key: ${result.stderr}`);
  }
  logBootstrap("secrets: encryption key generated");
  return result.stdout.trim();
}
