"""add client invoicing module

Revision ID: 17a92647cfd4
Revises: 98d00303a6e7
Create Date: 2026-07-20 09:55:04.374605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17a92647cfd4'
down_revision: Union[str, None] = '98d00303a6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('draft', 'sent', 'part_paid', 'paid', 'overdue', 'void', 'written_off', name='invoicestatus'), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal_kobo', sa.Integer(), nullable=False),
    sa.Column('disbursements_kobo', sa.Integer(), nullable=False),
    sa.Column('total_kobo', sa.Integer(), nullable=False),
    sa.Column('net_payable_kobo', sa.Integer(), nullable=False),
    sa.Column('amount_paid_kobo', sa.Integer(), nullable=False),
    sa.Column('vat_kobo', sa.Integer(), nullable=False),
    sa.Column('wht_kobo', sa.Integer(), nullable=False),
    sa.Column('vat_enabled', sa.Boolean(), nullable=False),
    sa.Column('wht_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_bill_of_charges', sa.Boolean(), nullable=False),
    sa.Column('served_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'number', name='uq_invoices_org_number')
    )
    op.create_index(op.f('ix_invoices_client_id'), 'invoices', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoices_number'), 'invoices', ['number'], unique=False)
    op.create_index(op.f('ix_invoices_organisation_id'), 'invoices', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('fee_arrangements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('fixed', 'retainer', 'scale', 'milestone', 'recovery', 'appearance', name='feearrangementtype'), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_arrangements_matter_id'), 'fee_arrangements', ['matter_id'], unique=False)
    op.create_index(op.f('ix_fee_arrangements_organisation_id'), 'fee_arrangements', ['organisation_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount_kobo', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('paystack', 'bank_transfer', 'cash', 'cheque', name='paymentmethod'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('wht_withheld_kobo', sa.Integer(), nullable=True),
    sa.Column('wht_credit_note_received', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'reference', name='uq_payments_org_reference')
    )
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_organisation_id'), 'payments', ['organisation_id'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=True),
    sa.Column('fee_arrangement_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('professional_fee', 'disbursement', 'expense', name='lineitemkind'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_amount_kobo', sa.Integer(), nullable=False),
    sa.Column('amount_kobo', sa.Integer(), nullable=False),
    sa.Column('is_vatable', sa.Boolean(), nullable=False),
    sa.Column('is_wht_applicable', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fee_arrangement_id'], ['fee_arrangements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_line_items_invoice_id'), 'invoice_line_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_line_items_matter_id'), 'invoice_line_items', ['matter_id'], unique=False)
    op.create_index(op.f('ix_invoice_line_items_organisation_id'), 'invoice_line_items', ['organisation_id'], unique=False)
    op.create_table('disbursements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('agency', 'recharge', name='disbursementtype'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount_kobo', sa.Integer(), nullable=False),
    sa.Column('incurred_at', sa.Date(), nullable=False),
    sa.Column('invoiced', sa.Boolean(), nullable=False),
    sa.Column('invoice_line_item_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_line_item_id'], ['invoice_line_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disbursements_matter_id'), 'disbursements', ['matter_id'], unique=False)
    op.create_index(op.f('ix_disbursements_organisation_id'), 'disbursements', ['organisation_id'], unique=False)
    op.add_column('clients', sa.Column('client_type', sa.String(length=20), nullable=False, server_default='individual'))
    op.add_column('clients', sa.Column('tin', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('vat_registered', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('clients', sa.Column('billing_address', sa.Text(), nullable=True))
    op.add_column('organisations', sa.Column('tin', sa.String(length=50), nullable=True))
    op.add_column('organisations', sa.Column('vat_reg_no', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisations', 'vat_reg_no')
    op.drop_column('organisations', 'tin')
    op.drop_column('clients', 'billing_address')
    op.drop_column('clients', 'vat_registered')
    op.drop_column('clients', 'tin')
    op.drop_column('clients', 'client_type')
    op.drop_index(op.f('ix_disbursements_organisation_id'), table_name='disbursements')
    op.drop_index(op.f('ix_disbursements_matter_id'), table_name='disbursements')
    op.drop_table('disbursements')
    op.drop_index(op.f('ix_invoice_line_items_organisation_id'), table_name='invoice_line_items')
    op.drop_index(op.f('ix_invoice_line_items_matter_id'), table_name='invoice_line_items')
    op.drop_index(op.f('ix_invoice_line_items_invoice_id'), table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index(op.f('ix_payments_organisation_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_fee_arrangements_organisation_id'), table_name='fee_arrangements')
    op.drop_index(op.f('ix_fee_arrangements_matter_id'), table_name='fee_arrangements')
    op.drop_table('fee_arrangements')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_organisation_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_client_id'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
