"""add reports table

Revision ID: 18ded1ca8f17
Revises: bff5a88755e8
Create Date: 2026-04-03 18:35:28.756140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ded1ca8f17'
down_revision: Union[str, None] = 'bff5a88755e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('period_label', sa.String(length=100), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('drive_file_id', sa.String(length=255), nullable=True),
    sa.Column('drive_url', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_organisation_id'), 'reports', ['organisation_id'], unique=False)
    op.add_column('organisations', sa.Column('paystack_customer_code', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('organisations_stripe_customer_id_key'), 'organisations', type_='unique')
    op.create_unique_constraint(None, 'organisations', ['paystack_customer_code'])
    op.drop_column('organisations', 'stripe_customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisations', sa.Column('stripe_customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'organisations', type_='unique')
    op.create_unique_constraint(op.f('organisations_stripe_customer_id_key'), 'organisations', ['stripe_customer_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('organisations', 'paystack_customer_code')
    op.drop_index(op.f('ix_reports_organisation_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
