"""add oauth mfa and trial fields

Revision ID: 1f02534011e9
Revises: f953df00b430
Create Date: 2026-04-06 18:17:59.717081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f02534011e9'
down_revision: Union[str, None] = 'f953df00b430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_oauth_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('google_oauth_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('google_avatar_url', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('mfa_secret', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('mfa_backup_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_users_google_oauth_id'), 'users', ['google_oauth_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_oauth_id'), table_name='users')
    op.drop_column('users', 'mfa_backup_codes')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'mfa_secret')
    op.drop_column('users', 'google_avatar_url')
    op.drop_column('users', 'google_oauth_email')
    op.drop_column('users', 'google_oauth_id')
    # ### end Alembic commands ###
