"""add organisation branding fields

Revision ID: 6337396c7131
Revises: 8be959945cd2
Create Date: 2026-07-26 21:53:47.025284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6337396c7131'
down_revision: Union[str, None] = '8be959945cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisations', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('organisations', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('organisations', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('organisations', sa.Column('website', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisations', 'website')
    op.drop_column('organisations', 'phone')
    op.drop_column('organisations', 'address')
    op.drop_column('organisations', 'logo_url')
    # ### end Alembic commands ###
