"""Add report filters

Revision ID: 7ee105f193ae
Revises: a7b8c9d0e1f2
Create Date: 2026-07-15 15:58:22.495963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee105f193ae'
down_revision: Union[str, None] = 'a7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matter_notes_org_updated'), table_name='matter_notes')
    op.drop_index(op.f('ix_notifications_user_unread'), table_name='notifications')
    op.add_column('reports', sa.Column('client_id', sa.UUID(), nullable=True))
    op.add_column('reports', sa.Column('matter_id', sa.UUID(), nullable=True))
    op.add_column('reports', sa.Column('matter_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_reports_client_id'), 'reports', ['client_id'], unique=False)
    op.create_index(op.f('ix_reports_matter_id'), 'reports', ['matter_id'], unique=False)
    op.create_foreign_key(None, 'reports', 'matters', ['matter_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'reports', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_index(op.f('ix_reports_matter_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_client_id'), table_name='reports')
    op.drop_column('reports', 'matter_type')
    op.drop_column('reports', 'matter_id')
    op.drop_column('reports', 'client_id')
    op.create_index(op.f('ix_notifications_user_unread'), 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_index(op.f('ix_matter_notes_org_updated'), 'matter_notes', ['organisation_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###
