"""add audit log and idempotency keys

Revision ID: 8be959945cd2
Revises: 17a92647cfd4
Create Date: 2026-07-22 14:44:34.213081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8be959945cd2'
down_revision: Union[str, None] = '17a92647cfd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('entry_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_org_created', 'audit_logs', ['organisation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_organisation_id'), 'audit_logs', ['organisation_id'], unique=False)
    op.add_column('clients', sa.Column('idempotency_key', sa.String(length=100), nullable=True))
    op.create_unique_constraint('uq_clients_org_idempotency_key', 'clients', ['organisation_id', 'idempotency_key'])
    op.add_column('invoices', sa.Column('idempotency_key', sa.String(length=100), nullable=True))
    op.create_unique_constraint('uq_invoices_org_idempotency_key', 'invoices', ['organisation_id', 'idempotency_key'])
    op.add_column('matters', sa.Column('idempotency_key', sa.String(length=100), nullable=True))
    op.create_unique_constraint('uq_matters_org_idempotency_key', 'matters', ['organisation_id', 'idempotency_key'])
    op.add_column('tasks', sa.Column('idempotency_key', sa.String(length=100), nullable=True))
    op.create_unique_constraint('uq_tasks_org_idempotency_key', 'tasks', ['organisation_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tasks_org_idempotency_key', 'tasks', type_='unique')
    op.drop_column('tasks', 'idempotency_key')
    op.drop_constraint('uq_matters_org_idempotency_key', 'matters', type_='unique')
    op.drop_column('matters', 'idempotency_key')
    op.drop_constraint('uq_invoices_org_idempotency_key', 'invoices', type_='unique')
    op.drop_column('invoices', 'idempotency_key')
    op.drop_constraint('uq_clients_org_idempotency_key', 'clients', type_='unique')
    op.drop_column('clients', 'idempotency_key')
    op.drop_index(op.f('ix_audit_logs_organisation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_log_org_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
