"""add paystack subscription code

Revision ID: 98008db5357e
Revises: 7ee105f193ae
Create Date: 2026-07-16 17:18:49.577340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98008db5357e'
down_revision: Union[str, None] = '7ee105f193ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisations', sa.Column('paystack_subscription_code', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisations', 'paystack_subscription_code')
    # ### end Alembic commands ###
