"""add billing transactions ledger and subscription email token

Revision ID: b1a16dd30339
Revises: 98008db5357e
Create Date: 2026-07-17 00:05:12.835316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1a16dd30339'
down_revision: Union[str, None] = '98008db5357e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('paystack_reference', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('amount_kobo', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paystack_reference')
    )
    op.create_index(op.f('ix_billing_transactions_organisation_id'), 'billing_transactions', ['organisation_id'], unique=False)
    op.add_column('organisations', sa.Column('paystack_subscription_email_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisations', 'paystack_subscription_email_token')
    op.drop_index(op.f('ix_billing_transactions_organisation_id'), table_name='billing_transactions')
    op.drop_table('billing_transactions')
    # ### end Alembic commands ###
