"""add trial and feature flags

Revision ID: f6323dfbf99b
Revises: 1f02534011e9
Create Date: 2026-04-08 09:24:05.065550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6323dfbf99b'
down_revision: Union[str, None] = '1f02534011e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisations', sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organisations', sa.Column('trial_used', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('organisations', sa.Column('feature_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisations', 'feature_flags')
    op.drop_column('organisations', 'trial_used')
    op.drop_column('organisations', 'trial_ends_at')
    # ### end Alembic commands ###
