"""rename stripe_customer_id to paystack_customer_code

Revision ID: f953df00b430
Revises: 18ded1ca8f17
Create Date: 2026-04-03 18:47:13.190165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f953df00b430'
down_revision: Union[str, None] = '18ded1ca8f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
