// ============================================================================
// LegalOps - Mock Data
// Realistic Nigerian legal operations data for development/demo
// ============================================================================

import {
  UserRole,
  MatterType,
  MatterStatus,
  TaskStatus,
  TaskPriority,
  DocumentType,
  DocumentStatus,
} from './types';
import type {
  UserResponse,
  OrgResponse,
  ClientResponse,
  MatterResponse,
  TaskResponse,
  DocumentResponse,
  ActivityResponse,
  DashboardStats,
  Notification,
  Integration,
  BillingInfo,
  MatterEmail,
} from './types';

// ============================================================================
// Organisation
// ============================================================================

export const mockOrganisation: OrgResponse = {
  id: 'org-001',
  name: 'Adebayo, Okonkwo & Associates',
  slug: 'adebayo-okonkwo',
  email: 'info@adebayo-okonkwo.com.ng',
  phone: '+234 1 234 5678',
  address: '14th Floor, Civic Towers, Ozumba Mbadiwe Ave, Victoria Island, Lagos',
  website: 'www.adebayo-okonkwo.com.ng',
  rc_number: 'RC-1234567',
  plan: 'professional',
  member_count: 8,
  matter_count: 47,
  created_at: '2023-01-15T09:00:00Z',
};

// ============================================================================
// Users
// ============================================================================

export const mockUsers: UserResponse[] = [
  {
    id: 'user-001',
    email: 'chukwuma.adebayo@adebayo-okonkwo.com.ng',
    first_name: 'Chukwuma',
    last_name: 'Adebayo',
    phone: '+234 802 345 6789',
    role: UserRole.ADMIN,
    is_active: true,
    created_at: '2023-01-15T09:00:00Z',
  },
  {
    id: 'user-002',
    email: 'folake.okonkwo@adebayo-okonkwo.com.ng',
    first_name: 'Folake',
    last_name: 'Okonkwo',
    phone: '+234 803 456 7890',
    role: UserRole.ADMIN,
    is_active: true,
    created_at: '2023-01-15T09:00:00Z',
  },
  {
    id: 'user-003',
    email: 'emeka.nwosu@adebayo-okonkwo.com.ng',
    first_name: 'Emeka',
    last_name: 'Nwosu',
    phone: '+234 805 567 8901',
    role: UserRole.MEMBER,
    is_active: true,
    created_at: '2023-03-10T10:30:00Z',
  },
  {
    id: 'user-004',
    email: 'aminu.bello@adebayo-okonkwo.com.ng',
    first_name: 'Aminu',
    last_name: 'Bello',
    phone: '+234 806 678 9012',
    role: UserRole.MEMBER,
    is_active: true,
    created_at: '2023-05-20T14:00:00Z',
  },
  {
    id: 'user-005',
    email: 'chioma.eze@adebayo-okonkwo.com.ng',
    first_name: 'Chioma',
    last_name: 'Eze',
    phone: '+234 807 789 0123',
    role: UserRole.MEMBER,
    is_active: true,
    created_at: '2023-06-01T08:45:00Z',
  },
  {
    id: 'user-006',
    email: 'tunde.ogundimu@adebayo-okonkwo.com.ng',
    first_name: 'Tunde',
    last_name: 'Ogundimu',
    phone: '+234 808 890 1234',
    role: UserRole.MEMBER,
    is_active: true,
    created_at: '2023-08-15T11:20:00Z',
  },
  {
    id: 'user-007',
    email: 'nneka.obi@adebayo-okonkwo.com.ng',
    first_name: 'Nneka',
    last_name: 'Obi',
    phone: '+234 809 901 2345',
    role: UserRole.VIEWER,
    is_active: true,
    created_at: '2023-09-01T09:00:00Z',
  },
  {
    id: 'user-008',
    email: 'ibrahim.yusuf@adebayo-okonkwo.com.ng',
    first_name: 'Ibrahim',
    last_name: 'Yusuf',
    phone: '+234 810 012 3456',
    role: UserRole.VIEWER,
    is_active: false,
    created_at: '2023-04-12T16:30:00Z',
  },
];

// ============================================================================
// Clients
// ============================================================================

export const mockClients: ClientResponse[] = [
  {
    id: 'client-001',
    name: 'Zenith Bank Plc',
    type: 'corporate',
    email: 'legal@zenithbank.com',
    phone: '+234 1 271 5400',
    address: 'Plot 84, Ajose Adeogun Street, Victoria Island, Lagos',
    company_name: 'Zenith Bank Plc',
    rc_number: 'RC-372090',
    contact_person: 'Mrs. Adaeze Okafor',
    notes: 'Key banking client. Retainer agreement in place since 2022.',
    is_active: true,
    matter_count: 12,
    created_at: '2023-02-01T10:00:00Z',
    updated_at: '2024-11-15T14:30:00Z',
  },
  {
    id: 'client-002',
    name: 'Dangote Group',
    type: 'corporate',
    email: 'corporate.legal@dangote.com',
    phone: '+234 1 460 4400',
    address: '1st Avenue, Ikoyi, Lagos',
    company_name: 'Dangote Industries Limited',
    rc_number: 'RC-196878',
    contact_person: 'Barr. Musa Garba',
    notes: 'Multinational conglomerate. Handles cement, sugar, flour operations.',
    is_active: true,
    matter_count: 8,
    created_at: '2023-03-15T09:00:00Z',
    updated_at: '2024-10-20T11:00:00Z',
  },
  {
    id: 'client-003',
    name: 'Lagos State Government',
    type: 'corporate',
    email: 'attorney.general@lagosstate.gov.ng',
    phone: '+234 1 263 5581',
    address: 'Alausa, Ikeja, Lagos',
    company_name: 'Lagos State Ministry of Justice',
    contact_person: 'Mr. Kayode Odukoya',
    notes: 'Government contract for land dispute resolution and advisory.',
    is_active: true,
    matter_count: 5,
    created_at: '2023-05-10T08:00:00Z',
    updated_at: '2024-11-01T16:00:00Z',
  },
  {
    id: 'client-004',
    name: 'Mrs. Amina Ibrahim',
    type: 'individual',
    email: 'amina.ibrahim@gmail.com',
    phone: '+234 802 111 2222',
    address: '12 Aminu Kano Crescent, Wuse 2, Abuja',
    notes: 'Family law and property matters.',
    is_active: true,
    matter_count: 3,
    created_at: '2023-06-20T14:00:00Z',
    updated_at: '2024-09-10T10:00:00Z',
  },
  {
    id: 'client-005',
    name: 'MTN Nigeria Communications Plc',
    type: 'corporate',
    email: 'legal@mtn.com.ng',
    phone: '+234 803 100 0001',
    address: 'MTN Plaza, Falomo Bridge, Ikoyi, Lagos',
    company_name: 'MTN Nigeria Communications Plc',
    rc_number: 'RC-329498',
    contact_person: 'Barr. Funke Adeyemi',
    notes: 'Telecommunications regulatory and compliance matters.',
    is_active: true,
    matter_count: 7,
    created_at: '2023-07-01T09:30:00Z',
    updated_at: '2024-11-20T13:00:00Z',
  },
  {
    id: 'client-006',
    name: 'Chief Olumide Bakare',
    type: 'individual',
    email: 'o.bakare@bakareholdings.com',
    phone: '+234 803 333 4444',
    address: '5A Glover Road, Ikoyi, Lagos',
    notes: 'Property portfolio management and investment advisory.',
    is_active: true,
    matter_count: 4,
    created_at: '2023-08-05T11:00:00Z',
    updated_at: '2024-10-05T09:00:00Z',
  },
  {
    id: 'client-007',
    name: 'Seplat Energy Plc',
    type: 'corporate',
    email: 'legal@seplatenergy.com',
    phone: '+234 1 461 2800',
    address: '1A Ozumba Mbadiwe Ave, Victoria Island, Lagos',
    company_name: 'Seplat Petroleum Development Company Plc',
    rc_number: 'RC-991274',
    contact_person: 'Mr. Damilola Ogunlesi',
    notes: 'Oil & gas sector. Joint venture agreements and regulatory compliance.',
    is_active: true,
    matter_count: 6,
    created_at: '2023-09-15T10:00:00Z',
    updated_at: '2024-11-18T15:00:00Z',
  },
  {
    id: 'client-008',
    name: 'Interswitch Group',
    type: 'corporate',
    email: 'legal@interswitchgroup.com',
    phone: '+234 1 270 0600',
    address: 'Plot 1281, Oba Akran Ave, Ikeja, Lagos',
    company_name: 'Interswitch Limited',
    rc_number: 'RC-438825',
    contact_person: 'Mrs. Yetunde Akindele',
    notes: 'Fintech and payments regulatory matters.',
    is_active: false,
    matter_count: 2,
    created_at: '2023-04-10T13:00:00Z',
    updated_at: '2024-06-30T10:00:00Z',
  },
];

// ============================================================================
// Matters
// ============================================================================

export const mockMatters: MatterResponse[] = [
  {
    id: 'matter-001',
    title: 'Zenith Bank v. Sterling Finance Ltd — Loan Recovery',
    description: 'Recovery of N2.5 billion facility granted to Sterling Finance Ltd. Matter pending before the Federal High Court, Lagos Division.',
    matter_number: 'MAT-2024-001',
    matter_type: MatterType.LITIGATION,
    status: MatterStatus.OPEN,
    priority: TaskPriority.HIGH,
    court: 'Federal High Court, Lagos Division',
    case_number: 'FHC/L/CS/2024/0234',
    judge: 'Hon. Justice A.O. Mohammed',
    opposing_counsel: 'Prof. Ganiyu Obi, SAN',
    filing_date: '2024-02-15',
    hearing_date: '2025-02-10',
    next_action: 'File reply to statement of defence',
    next_action_date: '2025-01-28',
    estimated_value: 2500000000,
    currency: 'NGN',
    tags: ['banking', 'loan-recovery', 'high-court'],
    is_billable: true,
    billed_amount: 45000000,
    client_id: 'client-001',
    client: mockClients[0],
    assigned_to: 'user-001',
    assignee: mockUsers[0],
    task_count: 6,
    document_count: 14,
    created_at: '2024-02-15T09:00:00Z',
    updated_at: '2024-12-20T16:45:00Z',
  },
  {
    id: 'matter-002',
    title: 'Dangote Cement — Environmental Compliance Review',
    description: 'Comprehensive review of environmental compliance for Dangote Cement operations in Ibese, Ogun State. Liaising with NESREA and FMEnv.',
    matter_number: 'MAT-2024-002',
    matter_type: MatterType.COMPLIANCE,
    status: MatterStatus.IN_REVIEW,
    priority: TaskPriority.MEDIUM,
    next_action: 'Finalize compliance report for NESREA submission',
    next_action_date: '2025-01-25',
    estimated_value: 15000000,
    currency: 'NGN',
    tags: ['compliance', 'environmental', 'manufacturing'],
    is_billable: true,
    billed_amount: 8000000,
    client_id: 'client-002',
    client: mockClients[1],
    assigned_to: 'user-004',
    assignee: mockUsers[3],
    task_count: 4,
    document_count: 8,
    created_at: '2024-03-01T10:00:00Z',
    updated_at: '2024-12-18T14:30:00Z',
  },
  {
    id: 'matter-003',
    title: 'Lagos State — Land Acquisition & Compensation Advisory',
    description: 'Advisory on compulsory land acquisition for the Lagos Red Line Rail project. Assessment of compensation claims from affected property owners.',
    matter_number: 'MAT-2024-003',
    matter_type: MatterType.ADVISORY,
    status: MatterStatus.OPEN,
    priority: TaskPriority.HIGH,
    next_action: 'Review compensation valuation reports',
    next_action_date: '2025-01-22',
    estimated_value: 25000000,
    currency: 'NGN',
    tags: ['government', 'land-acquisition', 'infrastructure'],
    is_billable: true,
    client_id: 'client-003',
    client: mockClients[2],
    assigned_to: 'user-002',
    assignee: mockUsers[1],
    task_count: 5,
    document_count: 11,
    created_at: '2024-04-10T09:00:00Z',
    updated_at: '2024-12-19T11:00:00Z',
  },
  {
    id: 'matter-004',
    title: 'Ibrahim v. Ibrahim — Divorce & Custody Proceedings',
    description: 'Dissolution of marriage and custody of 3 minor children. Matter before the Ikeja High Court.',
    matter_number: 'MAT-2024-004',
    matter_type: MatterType.LITIGATION,
    status: MatterStatus.PENDING,
    priority: TaskPriority.MEDIUM,
    court: 'High Court of Lagos State, Ikeja Division',
    case_number: 'IKD/2024/FM/0456',
    judge: 'Hon. Justice T.O. Adeyemi',
    filing_date: '2024-05-20',
    hearing_date: '2025-01-30',
    next_action: 'Prepare affidavit of means',
    next_action_date: '2025-01-20',
    estimated_value: 5000000,
    currency: 'NGN',
    tags: ['family-law', 'divorce', 'custody'],
    is_billable: true,
    client_id: 'client-004',
    client: mockClients[3],
    assigned_to: 'user-005',
    assignee: mockUsers[4],
    task_count: 3,
    document_count: 7,
    created_at: '2024-05-20T14:00:00Z',
    updated_at: '2024-12-15T10:00:00Z',
  },
  {
    id: 'matter-005',
    title: 'MTN Nigeria — NCC License Renewal & Compliance',
    description: 'Regulatory advisory for MTN Nigeria\'s telecommunications license renewal with the Nigerian Communications Commission.',
    matter_number: 'MAT-2024-005',
    matter_type: MatterType.COMPLIANCE,
    status: MatterStatus.OPEN,
    priority: TaskPriority.HIGH,
    next_action: 'Submit license renewal application to NCC',
    next_action_date: '2025-02-01',
    estimated_value: 50000000,
    currency: 'NGN',
    tags: ['telecoms', 'NCC', 'license'],
    is_billable: true,
    billed_amount: 20000000,
    client_id: 'client-005',
    client: mockClients[4],
    assigned_to: 'user-003',
    assignee: mockUsers[2],
    task_count: 7,
    document_count: 16,
    created_at: '2024-06-01T09:30:00Z',
    updated_at: '2024-12-22T09:00:00Z',
  },
  {
    id: 'matter-006',
    title: 'Bakare Holdings — Commercial Property Acquisition',
    description: 'Due diligence and transaction structuring for acquisition of a 12-storey commercial property on Victoria Island, Lagos.',
    matter_number: 'MAT-2024-006',
    matter_type: MatterType.TRANSACTIONAL,
    status: MatterStatus.IN_REVIEW,
    priority: TaskPriority.MEDIUM,
    next_action: 'Complete deed of assignment review',
    next_action_date: '2025-01-24',
    estimated_value: 7500000000,
    currency: 'NGN',
    tags: ['property', 'acquisition', 'due-diligence'],
    is_billable: true,
    billed_amount: 15000000,
    client_id: 'client-006',
    client: mockClients[5],
    assigned_to: 'user-001',
    assignee: mockUsers[0],
    task_count: 5,
    document_count: 9,
    created_at: '2024-07-10T11:00:00Z',
    updated_at: '2024-12-21T15:30:00Z',
  },
  {
    id: 'matter-007',
    title: 'Seplat Energy — Joint Operating Agreement Review',
    description: 'Review and amendment of Joint Operating Agreement (JOA) between Seplat and NPDC for Oil Mining Lease (OML) 30.',
    matter_number: 'MAT-2024-007',
    matter_type: MatterType.TRANSACTIONAL,
    status: MatterStatus.OPEN,
    priority: TaskPriority.HIGH,
    next_action: 'Circulate amended JOA draft to parties',
    next_action_date: '2025-01-27',
    estimated_value: 35000000,
    currency: 'NGN',
    tags: ['oil-gas', 'JOA', 'OML-30'],
    is_billable: true,
    client_id: 'client-007',
    client: mockClients[6],
    assigned_to: 'user-006',
    assignee: mockUsers[5],
    task_count: 4,
    document_count: 6,
    created_at: '2024-08-15T10:00:00Z',
    updated_at: '2024-12-20T12:00:00Z',
  },
  {
    id: 'matter-008',
    title: 'Zenith Bank — CBN Regulatory Compliance Audit',
    description: 'Internal audit preparation and regulatory compliance review in response to CBN circular on risk management framework.',
    matter_number: 'MAT-2024-008',
    matter_type: MatterType.COMPLIANCE,
    status: MatterStatus.PENDING,
    priority: TaskPriority.HIGH,
    next_action: 'Prepare compliance gap analysis report',
    next_action_date: '2025-01-23',
    estimated_value: 20000000,
    currency: 'NGN',
    tags: ['banking', 'CBN', 'regulatory', 'audit'],
    is_billable: true,
    client_id: 'client-001',
    client: mockClients[0],
    assigned_to: 'user-002',
    assignee: mockUsers[1],
    task_count: 6,
    document_count: 10,
    created_at: '2024-09-01T09:00:00Z',
    updated_at: '2024-12-19T14:00:00Z',
  },
  {
    id: 'matter-009',
    title: 'Dangote Group — Trade Mark Portfolio Management',
    description: 'Registration, renewal, and enforcement of trade marks across Nigeria for Dangote Group products.',
    matter_number: 'MAT-2024-009',
    matter_type: MatterType.ADVISORY,
    status: MatterStatus.OPEN,
    priority: TaskPriority.LOW,
    next_action: 'File trade mark renewal for DANGOTE SALT',
    next_action_date: '2025-03-15',
    estimated_value: 10000000,
    currency: 'NGN',
    tags: ['IP', 'trademark', 'brand-protection'],
    is_billable: true,
    client_id: 'client-002',
    client: mockClients[1],
    assigned_to: 'user-005',
    assignee: mockUsers[4],
    task_count: 3,
    document_count: 22,
    created_at: '2024-04-20T10:00:00Z',
    updated_at: '2024-12-10T09:00:00Z',
  },
  {
    id: 'matter-010',
    title: 'MTN Nigeria — Consumer Protection Class Action Defence',
    description: 'Defence of class action claim by Consumer Protection Council regarding data billing practices.',
    matter_number: 'MAT-2024-010',
    matter_type: MatterType.LITIGATION,
    status: MatterStatus.INTAKE,
    priority: TaskPriority.MEDIUM,
    next_action: 'Initial case assessment and strategy memo',
    next_action_date: '2025-01-30',
    estimated_value: 30000000,
    currency: 'NGN',
    tags: ['telecoms', 'consumer-protection', 'class-action'],
    is_billable: true,
    client_id: 'client-005',
    client: mockClients[4],
    assigned_to: 'user-001',
    assignee: mockUsers[0],
    task_count: 2,
    document_count: 3,
    created_at: '2024-12-01T11:00:00Z',
    updated_at: '2024-12-18T16:00:00Z',
  },
  {
    id: 'matter-011',
    title: 'Mrs. Ibrahim — Property Title Perfection',
    description: 'Perfection of title documents for properties located in Maitama and Asokoro, Abuja. Includes Governor\'s Consent and registration.',
    matter_number: 'MAT-2024-011',
    matter_type: MatterType.DRAFTING,
    status: MatterStatus.OPEN,
    priority: TaskPriority.LOW,
    tags: ['property', 'title-perfection', 'abuja'],
    is_billable: true,
    billed_amount: 3500000,
    client_id: 'client-004',
    client: mockClients[3],
    assigned_to: 'user-004',
    assignee: mockUsers[3],
    task_count: 4,
    document_count: 8,
    created_at: '2024-06-15T14:00:00Z',
    updated_at: '2024-11-20T10:00:00Z',
  },
  {
    id: 'matter-012',
    title: 'Seplat Energy — Community Development Agreement',
    description: 'Drafting and negotiation of Community Development Agreement (CDA) with host communities in Delta State.',
    matter_number: 'MAT-2024-012',
    matter_type: MatterType.DRAFTING,
    status: MatterStatus.CLOSED,
    priority: TaskPriority.LOW,
    tags: ['oil-gas', 'CDA', 'community'],
    is_billable: true,
    billed_amount: 12000000,
    client_id: 'client-007',
    client: mockClients[6],
    assigned_to: 'user-006',
    assignee: mockUsers[5],
    task_count: 0,
    document_count: 5,
    created_at: '2024-03-20T10:00:00Z',
    updated_at: '2024-10-30T14:00:00Z',
  },
];

// ============================================================================
// Tasks
// ============================================================================

export const mockTasks: TaskResponse[] = [
  {
    id: 'task-001',
    title: 'Draft reply to statement of defence',
    description: 'Prepare and file reply to Sterling Finance\'s statement of defence in the loan recovery matter.',
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.HIGH,
    assigned_to: 'user-001',
    due_date: '2025-01-28T17:00:00Z',
    matter_id: 'matter-001',
    matter: mockMatters[0],
    assignee: mockUsers[0],
    tags: ['court-filing', 'pleadings'],
    created_at: '2024-12-15T09:00:00Z',
    updated_at: '2024-12-22T11:00:00Z',
  },
  {
    id: 'task-002',
    title: 'Review witness statements for Zenith v. Sterling',
    description: 'Review and authenticate all witness statements from bank officials.',
    status: TaskStatus.TODO,
    priority: TaskPriority.HIGH,
    assigned_to: 'user-003',
    due_date: '2025-01-25T17:00:00Z',
    matter_id: 'matter-001',
    matter: mockMatters[0],
    assignee: mockUsers[2],
    created_at: '2024-12-16T10:00:00Z',
    updated_at: '2024-12-16T10:00:00Z',
  },
  {
    id: 'task-003',
    title: 'Finalize NESREA compliance report',
    description: 'Complete the environmental compliance gap analysis report for Dangote Cement Ibese.',
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.MEDIUM,
    assigned_to: 'user-004',
    due_date: '2025-01-25T17:00:00Z',
    matter_id: 'matter-002',
    matter: mockMatters[1],
    assignee: mockUsers[3],
    created_at: '2024-12-10T09:00:00Z',
    updated_at: '2024-12-20T14:00:00Z',
  },
  {
    id: 'task-004',
    title: 'Engage NESREA environmental consultant',
    description: 'Schedule meeting with NESREA accredited environmental consultant for site assessment.',
    status: TaskStatus.DONE,
    priority: TaskPriority.MEDIUM,
    assigned_to: 'user-004',
    due_date: '2024-12-20T17:00:00Z',
    completed_at: '2024-12-18T15:00:00Z',
    matter_id: 'matter-002',
    matter: mockMatters[1],
    assignee: mockUsers[3],
    created_at: '2024-12-05T11:00:00Z',
    updated_at: '2024-12-18T15:00:00Z',
  },
  {
    id: 'task-005',
    title: 'Review compensation valuation reports',
    description: 'Evaluate property valuation reports from appointed valuers for Red Line Rail project.',
    status: TaskStatus.TODO,
    priority: TaskPriority.HIGH,
    assigned_to: 'user-002',
    due_date: '2025-01-22T17:00:00Z',
    matter_id: 'matter-003',
    matter: mockMatters[2],
    assignee: mockUsers[1],
    created_at: '2024-12-17T09:00:00Z',
    updated_at: '2024-12-17T09:00:00Z',
  },
  {
    id: 'task-006',
    title: 'Prepare affidavit of means',
    description: 'Draft affidavit of means for Mrs. Ibrahim\'s custody proceedings.',
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.MEDIUM,
    assigned_to: 'user-005',
    due_date: '2025-01-20T17:00:00Z',
    matter_id: 'matter-004',
    matter: mockMatters[3],
    assignee: mockUsers[4],
    created_at: '2024-12-18T14:00:00Z',
    updated_at: '2024-12-21T10:00:00Z',
  },
  {
    id: 'task-007',
    title: 'Submit NCC license renewal application',
    description: 'Compile and submit complete license renewal documentation to the Nigerian Communications Commission.',
    status: TaskStatus.TODO,
    priority: TaskPriority.HIGH,
    assigned_to: 'user-003',
    due_date: '2025-02-01T17:00:00Z',
    matter_id: 'matter-005',
    matter: mockMatters[4],
    assignee: mockUsers[2],
    tags: ['regulatory', 'filing'],
    created_at: '2024-12-19T09:00:00Z',
    updated_at: '2024-12-19T09:00:00Z',
  },
  {
    id: 'task-008',
    title: 'Prepare NCC compliance checklist',
    description: 'Develop comprehensive compliance checklist for all MTN Nigeria license conditions.',
    status: TaskStatus.DONE,
    priority: TaskPriority.MEDIUM,
    assigned_to: 'user-003',
    due_date: '2024-12-15T17:00:00Z',
    completed_at: '2024-12-14T16:00:00Z',
    matter_id: 'matter-005',
    matter: mockMatters[4],
    assignee: mockUsers[2],
    created_at: '2024-12-01T10:00:00Z',
    updated_at: '2024-12-14T16:00:00Z',
  },
  {
    id: 'task-009',
    title: 'Review deed of assignment — Victoria Island property',
    description: 'Complete review of deed of assignment for the 12-storey Victoria Island commercial property.',
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.MEDIUM,
    assigned_to: 'user-001',
    due_date: '2025-01-24T17:00:00Z',
    matter_id: 'matter-006',
    matter: mockMatters[5],
    assignee: mockUsers[0],
    created_at: '2024-12-15T11:00:00Z',
    updated_at: '2024-12-22T09:00:00Z',
  },
  {
    id: 'task-010',
    title: 'Conduct property search at Land Registry',
    description: 'Conduct search at the Lagos State Land Registry for the Victoria Island property.',
    status: TaskStatus.DONE,
    priority: TaskPriority.HIGH,
    assigned_to: 'user-006',
    due_date: '2024-12-10T17:00:00Z',
    completed_at: '2024-12-09T14:00:00Z',
    matter_id: 'matter-006',
    matter: mockMatters[5],
    assignee: mockUsers[5],
    created_at: '2024-12-02T09:00:00Z',
    updated_at: '2024-12-09T14:00:00Z',
  },
  {
    id: 'task-011',
    title: 'Circulate amended JOA draft to NPDC and Seplat',
    description: 'Finalize and distribute the amended Joint Operating Agreement for OML 30.',
    status: TaskStatus.TODO,
    priority: TaskPriority.HIGH,
    assigned_to: 'user-006',
    due_date: '2025-01-27T17:00:00Z',
    matter_id: 'matter-007',
    matter: mockMatters[6],
    assignee: mockUsers[5],
    created_at: '2024-12-20T10:00:00Z',
    updated_at: '2024-12-20T10:00:00Z',
  },
  {
    id: 'task-012',
    title: 'Prepare CBN compliance gap analysis report',
    description: 'Draft comprehensive gap analysis report for Zenith Bank\'s risk management framework compliance.',
    status: TaskStatus.TODO,
    priority: TaskPriority.HIGH,
    assigned_to: 'user-002',
    due_date: '2025-01-23T17:00:00Z',
    matter_id: 'matter-008',
    matter: mockMatters[7],
    assignee: mockUsers[1],
    created_at: '2024-12-19T14:00:00Z',
    updated_at: '2024-12-19T14:00:00Z',
  },
  {
    id: 'task-013',
    title: 'File trade mark renewal for DANGOTE SALT',
    description: 'Submit trade mark renewal application to the Nigerian Trade Marks Registry.',
    status: TaskStatus.TODO,
    priority: TaskPriority.LOW,
    assigned_to: 'user-005',
    due_date: '2025-03-15T17:00:00Z',
    matter_id: 'matter-009',
    matter: mockMatters[8],
    assignee: mockUsers[4],
    created_at: '2024-12-10T10:00:00Z',
    updated_at: '2024-12-10T10:00:00Z',
  },
  {
    id: 'task-014',
    title: 'Prepare case assessment memo — MTN class action',
    description: 'Draft initial case assessment and litigation strategy memorandum for the class action defence.',
    status: TaskStatus.TODO,
    priority: TaskPriority.MEDIUM,
    assigned_to: 'user-001',
    due_date: '2025-01-30T17:00:00Z',
    matter_id: 'matter-010',
    matter: mockMatters[9],
    assignee: mockUsers[0],
    created_at: '2024-12-01T11:00:00Z',
    updated_at: '2024-12-01T11:00:00Z',
  },
  {
    id: 'task-015',
    title: 'Process Governor\'s Consent — Maitama property',
    description: 'Process application for Governor\'s Consent at the FCT Land Registry, Abuja.',
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.LOW,
    assigned_to: 'user-004',
    due_date: '2025-02-15T17:00:00Z',
    matter_id: 'matter-011',
    matter: mockMatters[10],
    assignee: mockUsers[3],
    created_at: '2024-11-20T10:00:00Z',
    updated_at: '2024-12-15T09:00:00Z',
  },
  {
    id: 'task-016',
    title: 'Prepare Q4 billing summary for Zenith Bank',
    description: 'Compile and send Q4 2024 billing summary for all active Zenith Bank matters.',
    status: TaskStatus.TODO,
    priority: TaskPriority.MEDIUM,
    assigned_to: 'user-007',
    due_date: '2025-01-15T17:00:00Z',
    matter_id: 'matter-001',
    matter: mockMatters[0],
    assignee: mockUsers[6],
    tags: ['billing'],
    created_at: '2024-12-22T09:00:00Z',
    updated_at: '2024-12-22T09:00:00Z',
  },
  {
    id: 'task-017',
    title: 'Schedule team meeting — January 2025',
    description: 'Organize monthly firm-wide meeting to review matter status and billing.',
    status: TaskStatus.DONE,
    priority: TaskPriority.LOW,
    assigned_to: 'user-007',
    due_date: '2024-12-28T17:00:00Z',
    completed_at: '2024-12-27T11:00:00Z',
    created_at: '2024-12-15T14:00:00Z',
    updated_at: '2024-12-27T11:00:00Z',
  },
  {
    id: 'task-018',
    title: 'Review amended JOA clause 12.3 — Decommissioning',
    description: 'Legal review of decommissioning obligations under the amended JOA.',
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.HIGH,
    assigned_to: 'user-006',
    due_date: '2025-01-26T17:00:00Z',
    matter_id: 'matter-007',
    matter: mockMatters[6],
    assignee: mockUsers[5],
    created_at: '2024-12-21T10:00:00Z',
    updated_at: '2024-12-22T15:00:00Z',
  },
  {
    id: 'task-019',
    title: 'Draft engagement letter — new client onboarding',
    description: 'Prepare engagement letter template updates for 2025 with revised fee structure.',
    status: TaskStatus.TODO,
    priority: TaskPriority.LOW,
    assigned_to: 'user-002',
    due_date: '2025-01-31T17:00:00Z',
    created_at: '2024-12-20T14:00:00Z',
    updated_at: '2024-12-20T14:00:00Z',
  },
  {
    id: 'task-020',
    title: 'Research CBN circular on KYC/AML compliance 2024',
    description: 'Legal research and memo on the latest CBN circular regarding Know Your Customer and Anti-Money Laundering requirements.',
    status: TaskStatus.TODO,
    priority: TaskPriority.MEDIUM,
    assigned_to: 'user-003',
    due_date: '2025-01-29T17:00:00Z',
    matter_id: 'matter-008',
    matter: mockMatters[7],
    assignee: mockUsers[2],
    tags: ['research', 'banking-regulation'],
    created_at: '2024-12-22T11:00:00Z',
    updated_at: '2024-12-22T11:00:00Z',
  },
  {
    id: 'task-021',
    title: 'Overdue: Follow up on land registry search results',
    description: 'Follow up with Lagos State Land Registry on pending search results for Ikoyi property.',
    status: TaskStatus.TODO,
    priority: TaskPriority.HIGH,
    assigned_to: 'user-006',
    due_date: '2024-12-05T17:00:00Z',
    matter_id: 'matter-006',
    matter: mockMatters[5],
    assignee: mockUsers[5],
    tags: ['overdue', 'follow-up'],
    created_at: '2024-11-28T09:00:00Z',
    updated_at: '2024-12-10T16:00:00Z',
  },
  {
    id: 'task-022',
    title: 'Overdue: Submit CAC annual returns for Interswitch',
    description: 'File annual returns with Corporate Affairs Commission for Interswitch Limited.',
    status: TaskStatus.TODO,
    priority: TaskPriority.MEDIUM,
    assigned_to: 'user-004',
    due_date: '2024-12-31T17:00:00Z',
    matter_id: 'matter-006',
    matter: mockMatters[5],
    assignee: mockUsers[3],
    tags: ['overdue', 'CAC-filing'],
    created_at: '2024-12-15T10:00:00Z',
    updated_at: '2024-12-15T10:00:00Z',
  },
];

// ============================================================================
// Documents
// ============================================================================

export const mockDocuments: DocumentResponse[] = [
  {
    id: 'doc-001',
    title: 'Writ of Summons — Zenith v. Sterling Finance',
    description: 'Originating writ of summons for loan recovery action.',
    document_type: DocumentType.FILING,
    status: DocumentStatus.SIGNED,
    file_size: 245000,
    version: 3,
    matter_id: 'matter-001',
    matter: mockMatters[0],
    uploaded_by: 'user-001',
    uploader: mockUsers[0],
    created_at: '2024-02-15T09:00:00Z',
    updated_at: '2024-03-10T14:00:00Z',
  },
  {
    id: 'doc-002',
    title: 'Statement of Claim — Zenith v. Sterling Finance',
    description: 'Detailed statement of claim for N2.5bn loan recovery.',
    document_type: DocumentType.FILING,
    status: DocumentStatus.SIGNED,
    file_size: 890000,
    version: 2,
    matter_id: 'matter-001',
    matter: mockMatters[0],
    uploaded_by: 'user-001',
    uploader: mockUsers[0],
    created_at: '2024-02-20T10:00:00Z',
    updated_at: '2024-03-05T11:00:00Z',
  },
  {
    id: 'doc-003',
    title: 'Engagement Letter — Dangote Cement',
    description: 'Legal engagement letter for environmental compliance advisory.',
    document_type: DocumentType.ENGAGEMENT_LETTER,
    status: DocumentStatus.SIGNED,
    file_size: 156000,
    version: 1,
    matter_id: 'matter-002',
    matter: mockMatters[1],
    uploaded_by: 'user-002',
    uploader: mockUsers[1],
    created_at: '2024-03-01T10:00:00Z',
    updated_at: '2024-03-01T10:00:00Z',
  },
  {
    id: 'doc-004',
    title: 'NESREA Compliance Gap Analysis (Draft)',
    description: 'Draft environmental compliance gap analysis report for Ibese plant.',
    document_type: DocumentType.REPORT,
    status: DocumentStatus.DRAFT,
    file_size: 3200000,
    version: 2,
    matter_id: 'matter-002',
    matter: mockMatters[1],
    uploaded_by: 'user-004',
    uploader: mockUsers[3],
    created_at: '2024-11-15T09:00:00Z',
    updated_at: '2024-12-18T14:00:00Z',
  },
  {
    id: 'doc-005',
    title: 'Legal Memo — Land Acquisition Compensation Framework',
    description: 'Memo on legal framework for compulsory land acquisition under the LUA.',
    document_type: DocumentType.MEMO,
    status: DocumentStatus.SIGNED,
    file_size: 567000,
    version: 1,
    matter_id: 'matter-003',
    matter: mockMatters[2],
    uploaded_by: 'user-002',
    uploader: mockUsers[1],
    created_at: '2024-04-15T10:00:00Z',
    updated_at: '2024-04-15T10:00:00Z',
  },
  {
    id: 'doc-006',
    title: 'Divorce Petition — Ibrahim v. Ibrahim',
    description: 'Petition for dissolution of marriage filed at Ikeja High Court.',
    document_type: DocumentType.FILING,
    status: DocumentStatus.SIGNED,
    file_size: 340000,
    version: 2,
    matter_id: 'matter-004',
    matter: mockMatters[3],
    uploaded_by: 'user-005',
    uploader: mockUsers[4],
    created_at: '2024-05-20T14:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
  },
  {
    id: 'doc-007',
    title: 'NCC License Renewal Checklist',
    description: 'Comprehensive checklist for MTN Nigeria\'s telecommunications license renewal.',
    document_type: DocumentType.REPORT,
    status: DocumentStatus.SIGNED,
    file_size: 189000,
    version: 1,
    matter_id: 'matter-005',
    matter: mockMatters[4],
    uploaded_by: 'user-003',
    uploader: mockUsers[2],
    created_at: '2024-12-14T16:00:00Z',
    updated_at: '2024-12-14T16:00:00Z',
  },
  {
    id: 'doc-008',
    title: 'Deed of Assignment — Victoria Island Property',
    description: 'Draft deed of assignment for 12-storey commercial property at Victoria Island.',
    document_type: DocumentType.CONTRACT,
    status: DocumentStatus.PENDING_SIGNATURE,
    file_size: 780000,
    version: 4,
    matter_id: 'matter-006',
    matter: mockMatters[5],
    uploaded_by: 'user-001',
    uploader: mockUsers[0],
    created_at: '2024-09-20T11:00:00Z',
    updated_at: '2024-12-20T15:00:00Z',
  },
  {
    id: 'doc-009',
    title: 'Amended Joint Operating Agreement — OML 30',
    description: 'Third draft of the amended JOA between Seplat and NPDC.',
    document_type: DocumentType.CONTRACT,
    status: DocumentStatus.DRAFT,
    file_size: 4500000,
    version: 3,
    matter_id: 'matter-007',
    matter: mockMatters[6],
    uploaded_by: 'user-006',
    uploader: mockUsers[5],
    created_at: '2024-10-01T10:00:00Z',
    updated_at: '2024-12-21T10:00:00Z',
  },
  {
    id: 'doc-010',
    title: 'CBN Risk Management Circular Analysis',
    description: 'Analysis memo on CBN circular BSM/2024/Risk Management Framework.',
    document_type: DocumentType.MEMO,
    status: DocumentStatus.DRAFT,
    file_size: 420000,
    version: 1,
    matter_id: 'matter-008',
    matter: mockMatters[7],
    uploaded_by: 'user-002',
    uploader: mockUsers[1],
    created_at: '2024-12-18T14:00:00Z',
    updated_at: '2024-12-18T14:00:00Z',
  },
  {
    id: 'doc-011',
    title: 'Correspondence — NESREA Pre-inspection Notice',
    description: 'Letter from NESREA regarding scheduled environmental inspection.',
    document_type: DocumentType.CORRESPONDENCE,
    status: DocumentStatus.SIGNED,
    file_size: 98000,
    version: 1,
    matter_id: 'matter-002',
    matter: mockMatters[1],
    uploaded_by: 'user-004',
    uploader: mockUsers[3],
    created_at: '2024-11-28T09:00:00Z',
    updated_at: '2024-11-28T09:00:00Z',
  },
  {
    id: 'doc-012',
    title: 'Community Development Agreement — Delta State Host Communities',
    description: 'Final signed CDA between Seplat Energy and Delta State host communities.',
    document_type: DocumentType.CONTRACT,
    status: DocumentStatus.SIGNED,
    file_size: 2100000,
    version: 5,
    matter_id: 'matter-012',
    matter: mockMatters[11],
    uploaded_by: 'user-006',
    uploader: mockUsers[5],
    created_at: '2024-06-01T10:00:00Z',
    updated_at: '2024-10-30T14:00:00Z',
  },
];

// ============================================================================
// Activity Log
// ============================================================================

export const mockActivities: ActivityResponse[] = [
  {
    id: 'act-001',
    action: 'document.uploaded',
    entity_type: 'document',
    entity_id: 'doc-010',
    description: 'Folake Okonkwo uploaded "CBN Risk Management Circular Analysis"',
    user: mockUsers[1],
    created_at: '2024-12-22T14:30:00Z',
  },
  {
    id: 'act-002',
    action: 'task.updated',
    entity_type: 'task',
    entity_id: 'task-001',
    description: 'Chukwuma Adebayo updated task status to "In Progress"',
    user: mockUsers[0],
    created_at: '2024-12-22T11:00:00Z',
  },
  {
    id: 'act-003',
    action: 'matter.updated',
    entity_type: 'matter',
    entity_id: 'matter-001',
    description: 'Hearing date set for February 10, 2025 in Zenith v. Sterling Finance',
    user: mockUsers[0],
    created_at: '2024-12-22T09:00:00Z',
  },
  {
    id: 'act-004',
    action: 'document.uploaded',
    entity_type: 'document',
    entity_id: 'doc-009',
    description: 'Tunde Ogundimu uploaded version 3 of "Amended JOA — OML 30"',
    user: mockUsers[5],
    created_at: '2024-12-21T10:00:00Z',
  },
  {
    id: 'act-005',
    action: 'task.created',
    entity_type: 'task',
    entity_id: 'task-018',
    description: 'Tunde Ogundimu created task "Review amended JOA clause 12.3"',
    user: mockUsers[5],
    created_at: '2024-12-21T10:00:00Z',
  },
  {
    id: 'act-006',
    action: 'document.updated',
    entity_type: 'document',
    entity_id: 'doc-008',
    description: 'Deed of Assignment status changed to "Pending Signature"',
    user: mockUsers[0],
    created_at: '2024-12-20T15:00:00Z',
  },
  {
    id: 'act-007',
    action: 'task.created',
    entity_type: 'task',
    entity_id: 'task-020',
    description: 'Emeka Nwosu created task "Research CBN circular on KYC/AML"',
    user: mockUsers[2],
    created_at: '2024-12-22T11:00:00Z',
  },
  {
    id: 'act-008',
    action: 'task.created',
    entity_type: 'task',
    entity_id: 'task-016',
    description: 'Nneka Obi created task "Prepare Q4 billing summary for Zenith Bank"',
    user: mockUsers[6],
    created_at: '2024-12-22T09:00:00Z',
  },
  {
    id: 'act-009',
    action: 'task.created',
    entity_type: 'task',
    entity_id: 'task-011',
    description: 'Tunde Ogundimu created task "Circulate amended JOA draft"',
    user: mockUsers[5],
    created_at: '2024-12-20T10:00:00Z',
  },
  {
    id: 'act-010',
    action: 'matter.created',
    entity_type: 'matter',
    entity_id: 'matter-010',
    description: 'New matter created: MTN Nigeria — Consumer Protection Class Action Defence',
    user: mockUsers[0],
    created_at: '2024-12-01T11:00:00Z',
  },
  {
    id: 'act-011',
    action: 'client.updated',
    entity_type: 'client',
    entity_id: 'client-008',
    description: 'Interswitch Group status changed to "Inactive"',
    user: mockUsers[1],
    created_at: '2024-06-30T10:00:00Z',
  },
  {
    id: 'act-012',
    action: 'task.completed',
    entity_type: 'task',
    entity_id: 'task-017',
    description: 'Nneka Obi completed task "Schedule team meeting — January 2025"',
    user: mockUsers[6],
    created_at: '2024-12-27T11:00:00Z',
  },
];

// ============================================================================
// Matter Emails (linked Gmail threads)
// ============================================================================

export const mockEmails: MatterEmail[] = [
  {
    id: 'email-001',
    organisation_id: 'org-001',
    matter_id: 'matter-001',
    thread_id: 'thread-18a3f2c1d4e5',
    subject: 'Re: Hearing Notice — FHC/L/CS/2024/0234',
    body_text: 'Please be informed that the hearing in the above matter has been fixed for February 10, 2025 at 9:00AM before Hon. Justice A.O. Mohammed.',
    from_address: 'deputy.registrar@fhclagos.gov.ng',
    from_name: 'Deputy Registrar, FHC Lagos',
    to_addresses: ['chukwuma.adebayo@adebayo-okonkwo.com.ng'],
    direction: 'incoming',
    email_date: '2024-12-20T10:30:00Z',
    is_read: true,
    is_starred: true,
    has_attachments: true,
    created_at: '2024-12-20T11:00:00Z',
  },
  {
    id: 'email-002',
    organisation_id: 'org-001',
    matter_id: 'matter-001',
    thread_id: 'thread-18a3f2c1d4e5',
    subject: 'Re: Hearing Notice — FHC/L/CS/2024/0234',
    body_text: 'Thank you for the notice. We confirm appearance for the hearing date.',
    from_address: 'chukwuma.adebayo@adebayo-okonkwo.com.ng',
    from_name: 'Chukwuma Adebayo',
    to_addresses: ['deputy.registrar@fhclagos.gov.ng'],
    direction: 'outgoing',
    email_date: '2024-12-20T14:00:00Z',
    is_read: true,
    is_starred: false,
    has_attachments: false,
    created_at: '2024-12-20T14:30:00Z',
  },
  {
    id: 'email-003',
    organisation_id: 'org-001',
    matter_id: 'matter-005',
    thread_id: 'thread-27b4e3d2f5a6',
    subject: 'NCC License Renewal — Required Documentation',
    body_text: 'Dear Sir, following our discussion, please find attached the list of required documents for the Spectral License renewal. The deadline for submission is February 28, 2025.',
    from_address: 'license.renewal@mtn.com.ng',
    from_name: 'Funke Adeyemi — MTN Legal',
    to_addresses: ['emeka.nwosu@adebayo-okonkwo.com.ng'],
    direction: 'incoming',
    email_date: '2024-12-18T09:15:00Z',
    is_read: true,
    is_starred: false,
    has_attachments: true,
    created_at: '2024-12-18T10:00:00Z',
  },
  {
    id: 'email-004',
    organisation_id: 'org-001',
    matter_id: 'matter-007',
    thread_id: 'thread-38c5f4e3a6b7',
    subject: 'Amended JOA Draft — Comments from NPDC Legal',
    body_text: 'Please find attached NPDC\'s comments on the amended JOA draft (clause 12.3 regarding decommissioning obligations). They have requested a meeting to discuss further.',
    from_address: 'legal@npdc.gov.ng',
    from_name: 'Barr. Aisha Mohammed — NPDC Legal',
    to_addresses: ['tunde.ogundimu@adebayo-okonkwo.com.ng'],
    direction: 'incoming',
    email_date: '2024-12-19T16:45:00Z',
    is_read: false,
    is_starred: true,
    has_attachments: true,
    created_at: '2024-12-19T17:00:00Z',
  },
];

// ============================================================================
// Notifications
// ============================================================================

export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    title: 'Task Overdue',
    message: 'Follow up on land registry search results is overdue since Dec 5.',
    type: 'warning',
    is_read: false,
    entity_type: 'task',
    entity_id: 'task-021',
    link: '#/tasks',
    created_at: '2024-12-06T09:00:00Z',
  },
  {
    id: 'notif-002',
    title: 'Hearing Scheduled',
    message: 'Zenith v. Sterling Finance hearing set for February 10, 2025.',
    type: 'info',
    is_read: false,
    entity_type: 'matter',
    entity_id: 'matter-001',
    link: '#/matters/matter-001',
    created_at: '2024-12-22T09:00:00Z',
  },
  {
    id: 'notif-003',
    title: 'Document Pending Signature',
    message: 'Deed of Assignment for Victoria Island property is awaiting signatures.',
    type: 'info',
    is_read: true,
    entity_type: 'document',
    entity_id: 'doc-008',
    link: '#/matters/matter-006',
    created_at: '2024-12-20T15:00:00Z',
  },
  {
    id: 'notif-004',
    title: 'New Team Member',
    message: 'Tunde Ogundimu has been added to the team as a Member.',
    type: 'success',
    is_read: true,
    entity_type: 'user',
    entity_id: 'user-006',
    created_at: '2024-08-15T11:20:00Z',
  },
  {
    id: 'notif-005',
    title: 'Client Engagement',
    message: 'New matter MAT-2024-010 created for MTN Nigeria.',
    type: 'info',
    is_read: true,
    entity_type: 'matter',
    entity_id: 'matter-010',
    link: '#/matters/matter-010',
    created_at: '2024-12-01T11:00:00Z',
  },
];

// ============================================================================
// Integrations
// ============================================================================

export const mockIntegrations: Integration[] = [
  {
    id: 'int-001',
    name: 'Google Workspace',
    slug: 'google-workspace',
    description: 'Sync emails, calendar events, and Google Drive documents.',
    icon_url: '/integrations/google.svg',
    is_connected: true,
    connected_at: '2024-03-15T10:00:00Z',
  },
  {
    id: 'int-002',
    name: 'Microsoft Outlook',
    slug: 'microsoft-outlook',
    description: 'Sync Outlook emails and calendar with LegalOps.',
    icon_url: '/integrations/outlook.svg',
    is_connected: false,
  },
  {
    id: 'int-003',
    name: 'Paystack',
    slug: 'paystack',
    description: 'Process client payments and generate invoices via Paystack.',
    icon_url: '/integrations/paystack.svg',
    is_connected: true,
    connected_at: '2024-06-01T09:00:00Z',
  },
  {
    id: 'int-004',
    name: 'Slack',
    slug: 'slack',
    description: 'Get matter updates and task notifications in Slack channels.',
    icon_url: '/integrations/slack.svg',
    is_connected: false,
  },
];

// ============================================================================
// Billing Info
// ============================================================================

export const mockBillingInfo: BillingInfo = {
  plan: 'professional',
  current_period_start: '2024-10-01T00:00:00Z',
  current_period_end: '2025-01-31T23:59:59Z',
  member_count: 7,
  member_limit: 15,
  storage_used: 2.4,
  storage_limit: 50,
  matter_count: 47,
};

// ============================================================================
// Dashboard Stats
// ============================================================================

export const mockDashboardStats: DashboardStats = {
  total_matters: 47,
  open_matters: 24,
  pending_tasks: 8,
  overdue_tasks: 2,
  total_clients: 42,
  active_clients: 36,
  total_revenue: 156800000,
  pending_invoiced: 23000000,
  matters_by_type: {
    litigation: 18,
    compliance: 9,
    advisory: 8,
    transactional: 7,
    drafting: 5,
  },
  matters_by_status: {
    open: 24,
    pending: 8,
    in_review: 6,
    intake: 3,
    closed: 4,
    archived: 2,
  },
  recent_activities: mockActivities.slice(0, 8),
  upcoming_deadlines: mockTasks
    .filter((t) => t.due_date && t.status !== TaskStatus.DONE && t.status !== TaskStatus.CANCELLED)
    .sort((a, b) => new Date(a.due_date!).getTime() - new Date(b.due_date!).getTime())
    .slice(0, 6),
};

// ============================================================================
// Export all as default
// ============================================================================

const mockData = {
  organisation: mockOrganisation,
  users: mockUsers,
  clients: mockClients,
  matters: mockMatters,
  tasks: mockTasks,
  documents: mockDocuments,
  activities: mockActivities,
  notifications: mockNotifications,
  integrations: mockIntegrations,
  billingInfo: mockBillingInfo,
  dashboardStats: mockDashboardStats,
};

export default mockData;
